apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qnfe0rk7i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qnfe0rk7i-go 
  name: qnfe0rk7i-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qnfe0rk7i-go 
